[build]
  publish = "public"
  command = "hugo"
[context.production.environment]
  HUGO_VERSION = "0.58.1"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"
[context.branch-deploy.environment]
  HUGO_VERSION = "0.58.1"